/*

 GAMEOVERMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Bitbitjam2016\bitbit3\res\gameover.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameoverWidth 20
#define gameoverHeight 18
#define gameoverBank 0

extern unsigned char gameover[];

/* End of GAMEOVERMAP.H */
