/*

 SPLASH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title8.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splashmapWidth 20
#define splashmapHeight 18
#define splashmapBank 0

extern unsigned char splashmap[];

/* End of SPLASH.H */
