/*

 SPLASH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 20
   Tile set      : D:\Bitbitjam2016\bitbit3\res\title8.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splashmapWidth 18
#define splashmapHeight 20
#define splashmapBank 0

extern unsigned char splashmap[];

/* End of SPLASH.H */
