/*

 WINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title8.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define winmapWidth 20
#define winmapHeight 18
#define winmapBank 0

extern unsigned char winmap[];

/* End of WINMAP.H */
