/*

 SRC/BULLET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bulletBank 0

/* Super Gameboy palette 0 */
#define bulletSGBPal0c0 6076
#define bulletSGBPal0c1 8935
#define bulletSGBPal0c2 6596
#define bulletSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bulletSGBPal1c0 6076
#define bulletSGBPal1c1 8935
#define bulletSGBPal1c2 6596
#define bulletSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bulletSGBPal2c0 6076
#define bulletSGBPal2c1 8935
#define bulletSGBPal2c2 6596
#define bulletSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bulletSGBPal3c0 6076
#define bulletSGBPal3c1 8935
#define bulletSGBPal3c2 6596
#define bulletSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bulletCGBPal0c0 32767
#define bulletCGBPal0c1 22197
#define bulletCGBPal0c2 11627
#define bulletCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bulletCGBPal1c0 6076
#define bulletCGBPal1c1 8935
#define bulletCGBPal1c2 6596
#define bulletCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define bulletCGBPal2c0 6076
#define bulletCGBPal2c1 8935
#define bulletCGBPal2c2 6596
#define bulletCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define bulletCGBPal3c0 6076
#define bulletCGBPal3c1 8935
#define bulletCGBPal3c2 6596
#define bulletCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define bulletCGBPal4c0 6076
#define bulletCGBPal4c1 8935
#define bulletCGBPal4c2 6596
#define bulletCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bulletCGBPal5c0 6076
#define bulletCGBPal5c1 8935
#define bulletCGBPal5c2 6596
#define bulletCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bulletCGBPal6c0 6076
#define bulletCGBPal6c1 8935
#define bulletCGBPal6c2 6596
#define bulletCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bulletCGBPal7c0 6076
#define bulletCGBPal7c1 8935
#define bulletCGBPal7c2 6596
#define bulletCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bulletCGB[];
/* Start of tile array. */
extern unsigned char bullet[];

/* End of SRC/BULLET.H */
