/*

 SRC/BULLET.B5.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* */

	#include "bullet.h"

	const int bulletPAL[] = 

	{

	bulletCGBPal0c0,bulletCGBPal0c1,bulletCGBPal0c2,bulletCGBPal0c3,

	bulletCGBPal1c0,bulletCGBPal1c1,bulletCGBPal1c2,bulletCGBPal1c3,

	bulletCGBPal2c0,bulletCGBPal2c1,bulletCGBPal2c2,bulletCGBPal2c3,

	bulletCGBPal3c0,bulletCGBPal3c1,bulletCGBPal3c2,bulletCGBPal3c3,

	bulletCGBPal4c0,bulletCGBPal4c1,bulletCGBPal4c2,bulletCGBPal4c3,

	bulletCGBPal5c0,bulletCGBPal5c1,bulletCGBPal5c2,bulletCGBPal5c3,

	bulletCGBPal6c0,bulletCGBPal6c1,bulletCGBPal6c2,bulletCGBPal6c3,

	bulletCGBPal7c0,bulletCGBPal7c1,bulletCGBPal7c2,bulletCGBPal7c3,

	};/* */
const unsigned  char bulletCGB[] =
{
  0x00,0x00
};
/* Start of tile array. */
const unsigned  char bullet[] =
{
  0x00,0x00,0x00,0x00,0x7E,0x7E,0xFF,0x81,
  0xFF,0x81,0x7E,0x7E,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of SRC/BULLET.B5.C */
