/*

 SRC/ENEMY2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define enemy2Bank 0

/* Super Gameboy palette 0 */
#define enemy2SGBPal0c0 6076
#define enemy2SGBPal0c1 8935
#define enemy2SGBPal0c2 6596
#define enemy2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define enemy2SGBPal1c0 6076
#define enemy2SGBPal1c1 8935
#define enemy2SGBPal1c2 6596
#define enemy2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define enemy2SGBPal2c0 6076
#define enemy2SGBPal2c1 8935
#define enemy2SGBPal2c2 6596
#define enemy2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define enemy2SGBPal3c0 6076
#define enemy2SGBPal3c1 8935
#define enemy2SGBPal3c2 6596
#define enemy2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define enemy2CGBPal0c0 32733
#define enemy2CGBPal0c1 21140
#define enemy2CGBPal0c2 11627
#define enemy2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define enemy2CGBPal1c0 32733
#define enemy2CGBPal1c1 15294
#define enemy2CGBPal1c2 535
#define enemy2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define enemy2CGBPal2c0 6076
#define enemy2CGBPal2c1 8935
#define enemy2CGBPal2c2 6596
#define enemy2CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define enemy2CGBPal3c0 6076
#define enemy2CGBPal3c1 8935
#define enemy2CGBPal3c2 6596
#define enemy2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define enemy2CGBPal4c0 6076
#define enemy2CGBPal4c1 8935
#define enemy2CGBPal4c2 6596
#define enemy2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define enemy2CGBPal5c0 6076
#define enemy2CGBPal5c1 8935
#define enemy2CGBPal5c2 6596
#define enemy2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define enemy2CGBPal6c0 6076
#define enemy2CGBPal6c1 8935
#define enemy2CGBPal6c2 6596
#define enemy2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define enemy2CGBPal7c0 6076
#define enemy2CGBPal7c1 8935
#define enemy2CGBPal7c2 6596
#define enemy2CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char enemy2CGB[];
/* Start of tile array. */
extern unsigned char enemy2[];

/* End of SRC/ENEMY2.H */
