/*

 SRC/ENEMY.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 2

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define enemyBank 0

/* Super Gameboy palette 0 */
#define enemySGBPal0c0 6076
#define enemySGBPal0c1 8935
#define enemySGBPal0c2 6596
#define enemySGBPal0c3 5344

/* Super Gameboy palette 1 */
#define enemySGBPal1c0 6076
#define enemySGBPal1c1 8935
#define enemySGBPal1c2 6596
#define enemySGBPal1c3 5344

/* Super Gameboy palette 2 */
#define enemySGBPal2c0 6076
#define enemySGBPal2c1 8935
#define enemySGBPal2c2 6596
#define enemySGBPal2c3 5344

/* Super Gameboy palette 3 */
#define enemySGBPal3c0 6076
#define enemySGBPal3c1 8935
#define enemySGBPal3c2 6596
#define enemySGBPal3c3 5344

/* Gameboy Color palette 0 */
#define enemyCGBPal0c0 32733
#define enemyCGBPal0c1 21140
#define enemyCGBPal0c2 11627
#define enemyCGBPal0c3 0

/* Gameboy Color palette 1 */
#define enemyCGBPal1c0 32733
#define enemyCGBPal1c1 17972
#define enemyCGBPal1c2 189
#define enemyCGBPal1c3 0

/* Gameboy Color palette 2 */
#define enemyCGBPal2c0 6076
#define enemyCGBPal2c1 8935
#define enemyCGBPal2c2 6596
#define enemyCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define enemyCGBPal3c0 6076
#define enemyCGBPal3c1 8935
#define enemyCGBPal3c2 6596
#define enemyCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define enemyCGBPal4c0 6076
#define enemyCGBPal4c1 8935
#define enemyCGBPal4c2 6596
#define enemyCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define enemyCGBPal5c0 6076
#define enemyCGBPal5c1 8935
#define enemyCGBPal5c2 6596
#define enemyCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define enemyCGBPal6c0 6076
#define enemyCGBPal6c1 8935
#define enemyCGBPal6c2 6596
#define enemyCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define enemyCGBPal7c0 6076
#define enemyCGBPal7c1 8935
#define enemyCGBPal7c2 6596
#define enemyCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char enemyCGB[];
/* Start of tile array. */
extern unsigned char enemy[];

/* End of SRC/ENEMY.H */
