/*

 SRC/INV_PLATFORMS.B4.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* */

	#include "inv_platforms.h"

	const int inv_platformsPAL[] = 

	{

	inv_platformsCGBPal0c0,inv_platformsCGBPal0c1,inv_platformsCGBPal0c2,inv_platformsCGBPal0c3,

	inv_platformsCGBPal1c0,inv_platformsCGBPal1c1,inv_platformsCGBPal1c2,inv_platformsCGBPal1c3,

	inv_platformsCGBPal2c0,inv_platformsCGBPal2c1,inv_platformsCGBPal2c2,inv_platformsCGBPal2c3,

	inv_platformsCGBPal3c0,inv_platformsCGBPal3c1,inv_platformsCGBPal3c2,inv_platformsCGBPal3c3,

	inv_platformsCGBPal4c0,inv_platformsCGBPal4c1,inv_platformsCGBPal4c2,inv_platformsCGBPal4c3,

	inv_platformsCGBPal5c0,inv_platformsCGBPal5c1,inv_platformsCGBPal5c2,inv_platformsCGBPal5c3,

	inv_platformsCGBPal6c0,inv_platformsCGBPal6c1,inv_platformsCGBPal6c2,inv_platformsCGBPal6c3,

	inv_platformsCGBPal7c0,inv_platformsCGBPal7c1,inv_platformsCGBPal7c2,inv_platformsCGBPal7c3,

	};/* */
const unsigned  char inv_platformsCGB[] =
{
  0x03,0x03
};
/* Start of tile array. */
const unsigned  char inv_platforms[] =
{
  0xFF,0x7F,0x80,0x80,0x80,0xFF,0xFF,0x7F,
  0xE0,0x3F,0xF0,0x1E,0xF8,0x0E,0xFF,0x07,
  0xFF,0xFE,0x01,0x01,0x01,0xFF,0xFF,0xFE,
  0x07,0xFC,0x0F,0x78,0x1F,0x70,0xFF,0xE0
};

/* End of SRC/INV_PLATFORMS.B4.C */
