/*

 SRC/INV_PLATFORMS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define inv_platformsBank 0

/* Super Gameboy palette 0 */
#define inv_platformsSGBPal0c0 6076
#define inv_platformsSGBPal0c1 8935
#define inv_platformsSGBPal0c2 6596
#define inv_platformsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define inv_platformsSGBPal1c0 6076
#define inv_platformsSGBPal1c1 8935
#define inv_platformsSGBPal1c2 6596
#define inv_platformsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define inv_platformsSGBPal2c0 6076
#define inv_platformsSGBPal2c1 8935
#define inv_platformsSGBPal2c2 6596
#define inv_platformsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define inv_platformsSGBPal3c0 6076
#define inv_platformsSGBPal3c1 8935
#define inv_platformsSGBPal3c2 6596
#define inv_platformsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define inv_platformsCGBPal0c0 32767
#define inv_platformsCGBPal0c1 20083
#define inv_platformsCGBPal0c2 10570
#define inv_platformsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define inv_platformsCGBPal1c0 32767
#define inv_platformsCGBPal1c1 31282
#define inv_platformsCGBPal1c2 32010
#define inv_platformsCGBPal1c3 0

/* Gameboy Color palette 2 */
#define inv_platformsCGBPal2c0 32733
#define inv_platformsCGBPal2c1 32200
#define inv_platformsCGBPal2c2 32456
#define inv_platformsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define inv_platformsCGBPal3c0 14310
#define inv_platformsCGBPal3c1 20083
#define inv_platformsCGBPal3c2 4704
#define inv_platformsCGBPal3c3 0

/* Gameboy Color palette 4 */
#define inv_platformsCGBPal4c0 17022
#define inv_platformsCGBPal4c1 20083
#define inv_platformsCGBPal4c2 5407
#define inv_platformsCGBPal4c3 0

/* Gameboy Color palette 5 */
#define inv_platformsCGBPal5c0 21182
#define inv_platformsCGBPal5c1 9631
#define inv_platformsCGBPal5c2 121
#define inv_platformsCGBPal5c3 0

/* Gameboy Color palette 6 */
#define inv_platformsCGBPal6c0 15294
#define inv_platformsCGBPal6c1 14079
#define inv_platformsCGBPal6c2 337
#define inv_platformsCGBPal6c3 0

/* Gameboy Color palette 7 */
#define inv_platformsCGBPal7c0 32767
#define inv_platformsCGBPal7c1 20083
#define inv_platformsCGBPal7c2 31938
#define inv_platformsCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char inv_platformsCGB[];
/* Start of tile array. */
extern unsigned char inv_platforms[];

/* End of SRC/INV_PLATFORMS.H */
