/*

 SRC/LASER_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define laser_animBank 0

/* Super Gameboy palette 0 */
#define laser_animSGBPal0c0 6076
#define laser_animSGBPal0c1 8935
#define laser_animSGBPal0c2 6596
#define laser_animSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define laser_animSGBPal1c0 6076
#define laser_animSGBPal1c1 8935
#define laser_animSGBPal1c2 6596
#define laser_animSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define laser_animSGBPal2c0 6076
#define laser_animSGBPal2c1 8935
#define laser_animSGBPal2c2 6596
#define laser_animSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define laser_animSGBPal3c0 6076
#define laser_animSGBPal3c1 8935
#define laser_animSGBPal3c2 6596
#define laser_animSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define laser_animCGBPal0c0 32767
#define laser_animCGBPal0c1 20083
#define laser_animCGBPal0c2 10570
#define laser_animCGBPal0c3 0

/* Gameboy Color palette 1 */
#define laser_animCGBPal1c0 32767
#define laser_animCGBPal1c1 31282
#define laser_animCGBPal1c2 32010
#define laser_animCGBPal1c3 0

/* Gameboy Color palette 2 */
#define laser_animCGBPal2c0 32733
#define laser_animCGBPal2c1 32200
#define laser_animCGBPal2c2 32456
#define laser_animCGBPal2c3 0

/* Gameboy Color palette 3 */
#define laser_animCGBPal3c0 14310
#define laser_animCGBPal3c1 20083
#define laser_animCGBPal3c2 4704
#define laser_animCGBPal3c3 0

/* Gameboy Color palette 4 */
#define laser_animCGBPal4c0 17022
#define laser_animCGBPal4c1 20083
#define laser_animCGBPal4c2 5407
#define laser_animCGBPal4c3 0

/* Gameboy Color palette 5 */
#define laser_animCGBPal5c0 21182
#define laser_animCGBPal5c1 9631
#define laser_animCGBPal5c2 121
#define laser_animCGBPal5c3 0

/* Gameboy Color palette 6 */
#define laser_animCGBPal6c0 15294
#define laser_animCGBPal6c1 14079
#define laser_animCGBPal6c2 337
#define laser_animCGBPal6c3 0

/* Gameboy Color palette 7 */
#define laser_animCGBPal7c0 32767
#define laser_animCGBPal7c1 20083
#define laser_animCGBPal7c2 31938
#define laser_animCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char laser_animCGB[];
/* Start of tile array. */
extern unsigned char laser_anim[];

/* End of SRC/LASER_ANIM.H */
