/*

 SRC/MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 62 x 126
   Tile set      : rick_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 62
#define mapHeight 126
#define mapBank 0

#define map mapPLN0
extern unsigned char mapPLN0[];
extern unsigned char mapPLN1[];

/* End of SRC/MAP.H */
