/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 48
   Tile set      : tiles1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map1Width 80
#define map1Height 48
#define map1Bank 0

#define map1 map1PLN0
extern unsigned char map1PLN0[];
extern unsigned char map1PLN1[];

/* End of MAP1.H */
