/*

 SRC/MENUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : map_menu_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menumapWidth 20
#define menumapHeight 18
#define menumapBank 0

#define menumap menumapPLN0
extern unsigned char menumapPLN0[];
extern unsigned char menumapPLN1[];

/* End of SRC/MENUMAP.H */
