/*

 SRC/MENUTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 98

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define menutilesBank 0

/* Super Gameboy palette 0 */
#define menutilesSGBPal0c0 6076
#define menutilesSGBPal0c1 8935
#define menutilesSGBPal0c2 6596
#define menutilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define menutilesSGBPal1c0 6076
#define menutilesSGBPal1c1 8935
#define menutilesSGBPal1c2 6596
#define menutilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define menutilesSGBPal2c0 6076
#define menutilesSGBPal2c1 8935
#define menutilesSGBPal2c2 6596
#define menutilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define menutilesSGBPal3c0 6076
#define menutilesSGBPal3c1 8935
#define menutilesSGBPal3c2 6596
#define menutilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define menutilesCGBPal0c0 0
#define menutilesCGBPal0c1 32767
#define menutilesCGBPal0c2 26425
#define menutilesCGBPal0c3 19026

/* Gameboy Color palette 1 */
#define menutilesCGBPal1c0 31248
#define menutilesCGBPal1c1 25602
#define menutilesCGBPal1c2 11297
#define menutilesCGBPal1c3 5185

/* Gameboy Color palette 2 */
#define menutilesCGBPal2c0 32767
#define menutilesCGBPal2c1 22197
#define menutilesCGBPal2c2 10570
#define menutilesCGBPal2c3 98

/* Gameboy Color palette 3 */
#define menutilesCGBPal3c0 2911
#define menutilesCGBPal3c1 505
#define menutilesCGBPal3c2 1293
#define menutilesCGBPal3c3 98

/* Gameboy Color palette 4 */
#define menutilesCGBPal4c0 32767
#define menutilesCGBPal4c1 22197
#define menutilesCGBPal4c2 10570
#define menutilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define menutilesCGBPal5c0 32767
#define menutilesCGBPal5c1 22197
#define menutilesCGBPal5c2 10570
#define menutilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define menutilesCGBPal6c0 6076
#define menutilesCGBPal6c1 8935
#define menutilesCGBPal6c2 6596
#define menutilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define menutilesCGBPal7c0 6076
#define menutilesCGBPal7c1 8935
#define menutilesCGBPal7c2 6596
#define menutilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char menutilesCGB[];
/* Start of tile array. */
extern unsigned char menutiles[];

/* End of SRC/MENUTILES.H */
