/*

 SRC/PINCHO_ANIM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 15

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pincho_animBank 0
/* Start of tile array. */
extern unsigned char pincho_anim[];

/* End of SRC/PINCHO_ANIM.H */
