/*

 SRC/PLATFORM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define platformBank 0

/* Super Gameboy palette 0 */
#define platformSGBPal0c0 6076
#define platformSGBPal0c1 8935
#define platformSGBPal0c2 6596
#define platformSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define platformSGBPal1c0 6076
#define platformSGBPal1c1 8935
#define platformSGBPal1c2 6596
#define platformSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define platformSGBPal2c0 6076
#define platformSGBPal2c1 8935
#define platformSGBPal2c2 6596
#define platformSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define platformSGBPal3c0 6076
#define platformSGBPal3c1 8935
#define platformSGBPal3c2 6596
#define platformSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define platformCGBPal0c0 32767
#define platformCGBPal0c1 22197
#define platformCGBPal0c2 11627
#define platformCGBPal0c3 0

/* Gameboy Color palette 1 */
#define platformCGBPal1c0 6076
#define platformCGBPal1c1 8935
#define platformCGBPal1c2 6596
#define platformCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define platformCGBPal2c0 6076
#define platformCGBPal2c1 8935
#define platformCGBPal2c2 6596
#define platformCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define platformCGBPal3c0 6076
#define platformCGBPal3c1 8935
#define platformCGBPal3c2 6596
#define platformCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define platformCGBPal4c0 6076
#define platformCGBPal4c1 8935
#define platformCGBPal4c2 6596
#define platformCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define platformCGBPal5c0 6076
#define platformCGBPal5c1 8935
#define platformCGBPal5c2 6596
#define platformCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define platformCGBPal6c0 6076
#define platformCGBPal6c1 8935
#define platformCGBPal6c2 6596
#define platformCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define platformCGBPal7c0 6076
#define platformCGBPal7c1 8935
#define platformCGBPal7c2 6596
#define platformCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char platformCGB[];
/* Start of tile array. */
extern unsigned char platform[];

/* End of SRC/PLATFORM.H */
