/*

 SRC/PLAYER2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define player2Bank 0

/* Super Gameboy palette 0 */
#define player2SGBPal0c0 6076
#define player2SGBPal0c1 8935
#define player2SGBPal0c2 6596
#define player2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define player2SGBPal1c0 6076
#define player2SGBPal1c1 8935
#define player2SGBPal1c2 6596
#define player2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define player2SGBPal2c0 6076
#define player2SGBPal2c1 8935
#define player2SGBPal2c2 6596
#define player2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define player2SGBPal3c0 6076
#define player2SGBPal3c1 8935
#define player2SGBPal3c2 6596
#define player2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define player2CGBPal0c0 32733
#define player2CGBPal0c1 928
#define player2CGBPal0c2 703
#define player2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define player2CGBPal1c0 32733
#define player2CGBPal1c1 20254
#define player2CGBPal1c2 340
#define player2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define player2CGBPal2c0 32733
#define player2CGBPal2c1 928
#define player2CGBPal2c2 703
#define player2CGBPal2c3 0

/* Gameboy Color palette 3 */
#define player2CGBPal3c0 6076
#define player2CGBPal3c1 8935
#define player2CGBPal3c2 6596
#define player2CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define player2CGBPal4c0 6076
#define player2CGBPal4c1 8935
#define player2CGBPal4c2 6596
#define player2CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define player2CGBPal5c0 6076
#define player2CGBPal5c1 8935
#define player2CGBPal5c2 6596
#define player2CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define player2CGBPal6c0 6076
#define player2CGBPal6c1 8935
#define player2CGBPal6c2 6596
#define player2CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define player2CGBPal7c0 6076
#define player2CGBPal7c1 8935
#define player2CGBPal7c2 6596
#define player2CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char player2CGB[];
/* Start of tile array. */
extern unsigned char player2[];

/* End of SRC/PLAYER2.H */
