/*

 SRC/SHARK.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sharkBank 0

/* Super Gameboy palette 0 */
#define sharkSGBPal0c0 6076
#define sharkSGBPal0c1 8935
#define sharkSGBPal0c2 6596
#define sharkSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define sharkSGBPal1c0 6076
#define sharkSGBPal1c1 8935
#define sharkSGBPal1c2 6596
#define sharkSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sharkSGBPal2c0 6076
#define sharkSGBPal2c1 8935
#define sharkSGBPal2c2 6596
#define sharkSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sharkSGBPal3c0 6076
#define sharkSGBPal3c1 8935
#define sharkSGBPal3c2 6596
#define sharkSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sharkCGBPal0c0 32733
#define sharkCGBPal0c1 21140
#define sharkCGBPal0c2 11627
#define sharkCGBPal0c3 0

/* Gameboy Color palette 1 */
#define sharkCGBPal1c0 32733
#define sharkCGBPal1c1 17972
#define sharkCGBPal1c2 189
#define sharkCGBPal1c3 0

/* Gameboy Color palette 2 */
#define sharkCGBPal2c0 6076
#define sharkCGBPal2c1 8935
#define sharkCGBPal2c2 6596
#define sharkCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define sharkCGBPal3c0 6076
#define sharkCGBPal3c1 8935
#define sharkCGBPal3c2 6596
#define sharkCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define sharkCGBPal4c0 6076
#define sharkCGBPal4c1 8935
#define sharkCGBPal4c2 6596
#define sharkCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define sharkCGBPal5c0 6076
#define sharkCGBPal5c1 8935
#define sharkCGBPal5c2 6596
#define sharkCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sharkCGBPal6c0 6076
#define sharkCGBPal6c1 8935
#define sharkCGBPal6c2 6596
#define sharkCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sharkCGBPal7c0 6076
#define sharkCGBPal7c1 8935
#define sharkCGBPal7c2 6596
#define sharkCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char sharkCGB[];
/* Start of tile array. */
extern unsigned char shark[];

/* End of SRC/SHARK.H */
