/*

 SRC/TILES1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 210

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define tiles1Bank 0

/* Super Gameboy palette 0 */
#define tiles1SGBPal0c0 6076
#define tiles1SGBPal0c1 8935
#define tiles1SGBPal0c2 6596
#define tiles1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define tiles1SGBPal1c0 6076
#define tiles1SGBPal1c1 8935
#define tiles1SGBPal1c2 6596
#define tiles1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define tiles1SGBPal2c0 6076
#define tiles1SGBPal2c1 8935
#define tiles1SGBPal2c2 6596
#define tiles1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define tiles1SGBPal3c0 6076
#define tiles1SGBPal3c1 8935
#define tiles1SGBPal3c2 6596
#define tiles1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define tiles1CGBPal0c0 32767
#define tiles1CGBPal0c1 15855
#define tiles1CGBPal0c2 10570
#define tiles1CGBPal0c3 0

/* Gameboy Color palette 1 */
#define tiles1CGBPal1c0 32767
#define tiles1CGBPal1c1 32072
#define tiles1CGBPal1c2 28679
#define tiles1CGBPal1c3 0

/* Gameboy Color palette 2 */
#define tiles1CGBPal2c0 32733
#define tiles1CGBPal2c1 32200
#define tiles1CGBPal2c2 32456
#define tiles1CGBPal2c3 0

/* Gameboy Color palette 3 */
#define tiles1CGBPal3c0 14310
#define tiles1CGBPal3c1 15855
#define tiles1CGBPal3c2 4704
#define tiles1CGBPal3c3 0

/* Gameboy Color palette 4 */
#define tiles1CGBPal4c0 17022
#define tiles1CGBPal4c1 15855
#define tiles1CGBPal4c2 5407
#define tiles1CGBPal4c3 0

/* Gameboy Color palette 5 */
#define tiles1CGBPal5c0 21182
#define tiles1CGBPal5c1 9631
#define tiles1CGBPal5c2 121
#define tiles1CGBPal5c3 0

/* Gameboy Color palette 6 */
#define tiles1CGBPal6c0 15294
#define tiles1CGBPal6c1 14079
#define tiles1CGBPal6c2 337
#define tiles1CGBPal6c3 0

/* Gameboy Color palette 7 */
#define tiles1CGBPal7c0 32767
#define tiles1CGBPal7c1 15855
#define tiles1CGBPal7c2 31938
#define tiles1CGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char tiles1CGB[];
/* Start of tile array. */
extern unsigned char tiles1[];

/* End of SRC/TILES1.H */
