/*

 WIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : tiles1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapwinWidth 20
#define mapwinHeight 4
#define mapwinBank 0

#define mapwin mapwinPLN0
extern unsigned char mapwinPLN0[];
extern unsigned char mapwinPLN1[];

/* End of WIN.H */
