/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 39
   Tile set      : C:\Users\Zalo\Desktop\gameboy\galaxy\res\tileTest.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapTestWidth 100
#define mapTestHeight 39
#define mapTestBank 0

extern unsigned char mapTest[];

/* End of MAP.H */
