/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 200 x 36
   Tile set      : carnage.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level1Width 200
#define level1Height 36
#define level1Bank 0

extern unsigned char level1[];

/* End of MAP.H */
