/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 200 x 36
   Tile set      : carnage.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level2Width 200
#define level2Height 36
#define level2Bank 0

extern unsigned char level2[];

/* End of MAP2.H */
